### ISSUE TITLE
Ugly username when using Google authentication

### ISSUE THREAD

**Issue by leogermani** [PROCERGS/login-cidadao#282]
When you login via google, your username is shown as a huge number

Personal info:
11915986495610464ac199a5.95777064

**Comment by leogermani** [comment]
Issue aberta pela equipe do MiNC

https://github.com/culturagovbr/id-cultura/issues/30

**Comment by guilhermednt** [comment]
Actually I think we need to deprecate this feature, so instead of showing the username in the top bar we simply show the user's name. If the person didn't set a name we could show something like `<No name>`.

This, however, is not mutually exclusive. We should and will try to improve the username generation for Google login.

**Comment by guilhermednt** [comment]
@leogermani how about that? is it ok for you?

https://github.com/culturagovbr/id-cultura/issues/30

**Comment by guilhermednt** [comment]
This is now partially solved by #378

**Comment by leogermani** [comment]
ok. but do we really need a username at all?

**Comment by guilhermednt** [comment]
@leogermani no, that's why I deprecated it in #378 .
